name: uac_mcf_project
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.9
  intro_slider: ^2.3.3
  google_nav_bar: ^3.1.0
  floating_action_bubble: ^1.1.2
  multilevel_drawer: ^1.0.3
  country_code_picker: ^1.6.0
  nepali_date_picker: ^4.2.0+1
  webfeed: ^0.6.0
  intl: ^0.16.1
  http: ^0.12.2
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/téléchargement.jpeg
    - assets/62770407-relations-humaines-3d-illustration-isolé-sur-fond-blanc.jpg
    - assets/diplome-graduation-hat-isole-icone_25030-13391.jpg
    - assets/développement-article-borne-escamotable.jpg
    - assets/mcflogo.png
    - assets/icones/baseline_account_circle_black_18dp.png
    - assets/icones/baseline_contactless_white_18dp.png
    - assets/icones/baseline_clear_white_18dp.png
    - assets/icones/baseline_flight_white_18dp.png
    - assets/icones/baseline_developer_board_white_18dp.png
    - assets/icones/baseline_help_white_18dp.png
    - assets/mcf_uac.png
    - assets/icones/baseline_alternate_email_white_18dp.png
    - assets/icones/baseline_vpn_key_white_18dp.png
    - assets/illu-intro.svg
    - assets/ADMIN-APPROVED-USER-REGISTRATION.png
    - assets/beers.json
    - assets/ifrilogo.jpg
    - assets/XLarge-EPAC-UAC.jpg
    - assets/logoFAST.jpg
    - assets/téléchargé.jpg
    - assets/400149200417_6190.jpg
    - assets/Website-Banner-FR-1200x400.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
